---
windows_targets: &windows_targets
- "--"
- "@bazel_skylib//..."
# TODO: the following tests cannot be run remotely. fix them!
- "-@bazel_skylib//tests/native_binary:args_test"
- "-@bazel_skylib//tests/run_binary:run_bin_test"
- "-@bazel_skylib//tests/run_binary:run_script_test"
# TODO: this test only fails on windows due to a bug in Bazel
- "-@bazel_skylib//tests/native_binary/..."
targets: &targets
- "--"
- "@bazel_skylib//..."
# TODO: the following tests cannot be run remotely. fix them!
- "-@bazel_skylib//tests/native_binary:args_test"
- "-@bazel_skylib//tests/run_binary:run_bin_test"
- "-@bazel_skylib//tests/run_binary:run_script_test"
common: &common
  build_targets: *targets
  test_targets: *targets
buildifier: latest
tasks:
  macos:
    build_flags:
    - --incompatible_remap_main_repo
    setup:
    - python3.7 patch_repositories.py
    - python3.7 create_project_workspace.py --project=bazel_skylib
    test_flags:
    - --test_env=PATH
    <<: *common
  ubuntu1604:
    build_flags:
    - --incompatible_remap_main_repo
    setup:
    - python3.6 patch_repositories.py
    - python3.6 create_project_workspace.py --project=bazel_skylib
    test_flags:
    - --test_env=PATH
    <<: *common
  ubuntu1804:
    build_flags:
    - --incompatible_remap_main_repo
    setup:
    - python3.6 patch_repositories.py
    - python3.6 create_project_workspace.py --project=bazel_skylib
    test_flags:
    - --test_env=PATH
    <<: *common
  windows:
    build_flags:
    - --incompatible_remap_main_repo
    setup:
    - python.exe patch_repositories.py
    - python.exe create_project_workspace.py --project=bazel_skylib
    test_flags:
    - --test_env=LOCALAPPDATA
    build_targets: *windows_targets
    test_targets: *windows_targets
